//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.User_Pages {
    
    
    public partial class User_Main_Page {
        
        /// <summary>
        /// User_Main_page_Control11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Real_Estate_Management.User_Control.User_Main_page_Control1 User_Main_page_Control11;
    }
}
